include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style Rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    null_closures: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    provide_deprecation_message: true
    sized_box_for_whitespace: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: info
    deprecated_member_use: info
    invalid_annotation_target: ignore
    unrelated_type_equality_checks: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

